import { _electron as electron, chromium } from "playwright";
import assert from "node:assert/strict";
import { mkdir } from "node:fs/promises";
const env = { ...process.env, ALGOARENA_HEADLESS: "1" };
delete env.ELECTRON_RUN_AS_NODE;
const executablePath = process.env.ALGOARENA_TEST_EXE;
const launch = () => electron.launch({ ...(executablePath ? { executablePath, args: [] } : { args: ["."] }), env });
const health = 'http://127.0.0.1:8765/api/health';
let app = await launch();
let browser;
try {
  let launcher = await app.firstWindow();
  await launcher.locator('[data-target="desktop"]').waitFor();
  await launcher.locator('#language').selectOption('en');
  await launcher.getByRole('button', { name: /Open desktop app/ }).waitFor();
  assert(await launcher.evaluate(() => document.documentElement.scrollHeight <= innerHeight), 'launcher scroll');
  const studioOpened = app.waitForEvent('window');
  const launcherClosed = launcher.waitForEvent('close');
  await launcher.getByRole('button', { name: /Open desktop app/ }).click();
  const studio = await studioOpened;
  await studio.getByRole('button', { name: 'Run', exact: true }).waitFor();
  await launcherClosed;
  assert.equal(app.windows().length, 1, 'selector must be destroyed');
  await studio.getByRole('button', { name: 'Understand the modes' }).click();
  await studio.getByRole('button', { name: 'Got it', exact: true }).click();
  await studio.getByRole('button', { name: /Interactive tutorial/ }).click();
  await studio.getByRole('button', { name: 'Next →' }).click();
  await studio.getByRole('button', { name: 'Next →' }).click();
  await studio.getByLabel('generations', { exact: true }).fill('4');
  await studio.getByRole('button', { name: 'Run experiment', exact: true }).click();
  await studio.waitForFunction(() => document.querySelector('.status-label strong')?.textContent === 'Results available', null, { timeout: 60000 });
  await studio.getByRole('button', { name: 'Next →' }).click();
  await studio.getByRole('button', { name: 'Next →' }).click();
  await studio.getByRole('button', { name: 'Finish', exact: true }).click();
  await app.evaluate(({ session }) => {
    globalThis.downloadName = null;
    session.defaultSession.once('will-download', (_event, item) => { globalThis.downloadName = item.getFilename(); item.cancel(); });
  });
  await studio.getByRole('button', { name: /Reproducibility manifest/ }).click();
  for (let attempt = 0; attempt < 50 && !await app.evaluate(() => globalThis.downloadName); attempt++) await new Promise(resolve => setTimeout(resolve, 100));
  assert((await app.evaluate(() => globalThis.downloadName))?.endsWith('.json'));
  await studio.getByRole('combobox', { name: 'Language', exact: true }).selectOption('fr');
  await studio.getByRole('button', { name: 'Lancer', exact: true }).waitFor();
  assert.equal(await studio.locator('.status-label strong').textContent(), 'Résultats disponibles');
  await studio.reload();
  await studio.getByRole('button', { name: 'Lancer', exact: true }).waitFor();
  assert.equal(await studio.evaluate(() => document.documentElement.lang), 'fr');
  const closed = app.waitForEvent('close');
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].close());
  await closed;
  await assert.rejects(fetch(health), 'desktop close must stop engine');
  app = await launch(); launcher = await app.firstWindow();
  await launcher.getByRole('button', { name: /Ouvrir le navigateur/ }).waitFor();
  await app.evaluate(({ shell }) => { shell.openExternal = async () => { throw Error('Browser unavailable'); }; });
  await launcher.getByRole('button', { name: /Ouvrir le navigateur/ }).click();
  await launcher.getByRole('status').filter({ hasText: 'Browser unavailable' }).waitFor({timeout:60000});
  assert(!launcher.isClosed(), 'failed launch must retain selector for retry');
  await assert.rejects(fetch(health), 'failed browser launch must stop engine');
  await app.evaluate(({ shell, Tray }) => {
    globalThis.openedUrl = null;
    shell.openExternal = async url => { globalThis.openedUrl = url; };
    const original = Tray.prototype.setContextMenu;
    Tray.prototype.setContextMenu = function(menu) { globalThis.trayMenu = menu; return original.call(this, menu); };
  });
  const selectorClosed = launcher.waitForEvent('close');
  await launcher.getByRole('button', { name: /Ouvrir le navigateur/ }).click();
  await selectorClosed;
  assert.equal(app.windows().length, 0, 'web mode must have no selector window');
  assert((await fetch(health)).ok, 'browser engine should stay alive');
  const url = await app.evaluate(() => globalThis.openedUrl);
  assert.equal(new URL(url).searchParams.get('lang'), 'fr');
  browser = await chromium.launch();
  const page = await browser.newPage();
  await page.goto(url);
  await page.getByRole('combobox', { name: 'Langue', exact: true }).selectOption('en');
  await page.getByRole('button', { name: 'Run', exact: true }).waitFor();
  await page.reload();
  await page.getByRole('button', { name: 'Run', exact: true }).waitFor();
  await page.getByRole('button', {name:'Scenario',exact:true}).click();
  await page.getByRole('button', {name:'Open Simulate',exact:true}).click();
  await page.getByRole('heading', {name:'WORKFLOW AND DEPENDENCIES',exact:true}).waitFor();
  await page.getByRole('button', {name:'Pareto',exact:true}).click();
  for (const viewport of [{width:1366,height:768},{width:800,height:600}]) {
    await page.setViewportSize(viewport);
    const bounds = await page.getByRole('combobox', {name:'Language',exact:true}).boundingBox();
    assert(bounds && bounds.x >= 0 && bounds.x + bounds.width <= viewport.width, 'language selector clipped');
    await mkdir('reports', {recursive:true});
    await page.screenshot({path:`reports/studio-en-${viewport.width}.png`});
  }
  await page.close();
  assert((await fetch(health)).ok, 'closing tab should preserve tray controller');
  const done = app.waitForEvent('close');
  await app.evaluate(() => globalThis.trayMenu.items.find(item => item.label === 'Tout arrêter et quitter').click());
  await done;
  await assert.rejects(fetch(health), 'tray quit must stop engine');
  console.log('PASS: selector destroyed, desktop close stops engine, browser tray quit, FR/EN persistence, translated tutorial, calculation and export, responsive language button');
} finally { await browser?.close(); await app.close().catch(() => {}); }
